#' Create an rds file to hold the model's data and outputs.
#'
#' @param model_dir Directory name of model to be loaded
#' @param overwrite_rds_files Logical. If TRUE, overwrite the RDS file if it exists
#' @param ... Parameters passed to [load_iscam_files()]
#'
#' @return [base::invisible()]
#' @export
create_rds_file <- function(model_dir = NULL,
                            overwrite_rds_files = FALSE,
                            ...){

  stopifnot(!is.null(model_dir))

  if(!dir.exists(model_dir)){
    stop("The directory ", model_dir, " does not exist")
  }

  # The RDS file will have the same name as the directory it is in
  # rds_file <- file.path(model_dir, paste0(basename(model_dir), ".rds"))
  # The RDS file will have the same name as the directory it the model was in
  # and be placed one dir up so all RDS files are in one dir
  if(basename(model_dir) == "base"){
    rds_file <- file.path(model_dir, paste0(basename(model_dir), ".rds"))
  }else{
    prev_dir <- gsub("^(\\S+)/\\S+$", "\\1", model_dir)
    rds_file <- file.path(prev_dir, paste0(basename(model_dir), ".rds"))
  }
  if(file.exists(rds_file)){
    if(overwrite_rds_files){
      unlink(rds_file, force = TRUE)
    }else{
      message("Skipping ", rds_file, ". To overwrite it, set overwrite = TRUE")
      return(invisible())
    }
  }

  # If this point is reached, no RDs file exists so it has to be built from scratch
  model <- load_iscam_files(model_dir, ...)

  # Load retrospectives. If none are found or there is a problem, model$retros will be NA
  # model$retropath <- file.path(model_dir, retro.dir)
  # if(dir.exists(model$retropath)){
  #   model$retros <- fetch_retrospectives(model$retropath,
  #                                        retrospective_yrs)
  # }else{
  #   model$retros <- NA
  # }

  saveRDS(model, file = rds_file)
  message("Created a new RDS file in ", model_dir, "\n")
  invisible()
}

#' Load RDS file which was generated by [create_rds_file()]
#'
#' @param model_dir Directory name of model to be loaded
#'
#' @return The results of [base::readRDS()] or `NULL` if the file does not exist
#' @export
load_rds_file <- function(model_dir = NULL){

  stopifnot(!is.null(model_dir))
  if(basename(model_dir) == "base"){
    if(!dir.exists(model_dir)){
      stop("Error - the directory `", model_dir, "` does not exist.\n",
           call. = FALSE)
    }
    rds_file <- file.path(model_dir, paste0(basename(model_dir), ".rds"))
  }else{
    prev_dir <- gsub("^(\\S+)/\\S+$", "\\1", model_dir)
    if(!dir.exists(prev_dir)){
      stop("Error - the directory `", prev_dir, "` does not exist.\n",
           call. = FALSE)
    }
    rds_file <- file.path(prev_dir, paste0(basename(model_dir), ".rds"))
  }

  # The RDS file will have the same name as the directory it is in
  if(file.exists(rds_file)){
    return(readRDS(rds_file))
  }else{
    message("File `", rds_file, "` does not exist.\n",
            "Run create_rds_file(", model_dir, ") and try again.",
            call. = FALSE)
    return(NULL)
  }
}
