#' Write an ISCAM projection file (pfc file)
#'
#' @param fn The filename
#' @param proj_lst A list with the same structure as that returned by
#' [read_projection_file()]
#' @param overwrite If `TRUE`, overwrite the file if it exists
#'
#' @return Nothing
#' @export
write_projection_file <- function(fn,
                                  proj_lst,
                                  overwrite = FALSE){

  path <- dirname(fn)
  if(!dir.exists(path)){
    stop("The directory `", path, "` does not exist", call. = FALSE)
  }
  if(file.exists(fn) && !overwrite){
    stop("The file `", fn, "` exists. To overwrite it, call this function ",
         "again with `overwrite = TRUE`",
         call. = FALSE)
  }
  if(file.exists(fn)){
    unlink(fn, force = TRUE)
  }

  out <- c("# - This file was generated by the function gfiscamutils::write_projection_file()",
           "# ------------------------------------------------------------------------------",
           "# Projection file control (pfc)",
           "# ------------------------------------------------------------------------------",
           "#",
           "# Number of years to project",
           proj_lst$num.projyrs,
           "# Length of catch vector.",
           proj_lst$num.tac,
           "# TAC vector (thousand tonnes)")

  for(tac in proj_lst$tac.vec){
    out <- c(out, tac)
  }
  out <- c(out,
           "#",
           "# ------------------------------------------------------------------------------",
           "# Control options",
           "# ------------------------------------------------------------------------------",
           proj_lst$num.ctl.options)

  for(i in 1:proj_lst$num.ctl.options){
    out <- c(out, proj_lst$ctl.options[i, ])
  }
  out <- c(out,
           "#",
           proj_lst$eof)

  writeLines(out, fn)
  invisible()
}
