globalVariables(c(
"Age50",
"iscam.starter.file",
"biomass",
"Bed",
"CRS",
"Case",
"CaseType",
"abline",
"aggregate",
"allRegions",
"arrows",
"as_tibble",
"axis",
"bbox",
"bind_rows",
"block",
"box",
"catch",
"col2rgb",
"cols",
"crop",
"curr.func.name",
"curve",
"dbeta",
"dev.list",
"dgamma",
"distinct",
"dlnorm",
"dnorm",
"dunif",
"estphase",
"Eastings",
"Estimated",
"EstimatedValues",
"Female Age50",
"Female SD50",
"Male Age50",
"Male SD50",
"Female_P1",
"Female_P2",
"Male_P1",
"Male_P2",
"Group",
"index",
"Initial",
"InitialValues",
"Loc_Code",
"Location",
"LocationCode",
"LocationName",
"Location_Latitude",
"Location_Longitude",
"Log standardized residual",
"lowerci",
"upperci",
"sbt.x",
"sbt.y",
"Sex",
"SD50",
"model",
"Model",
"Northings",
"Parameter",
"Region",
"RegionName",
"SAR",
"Section",
"SensitivityCase",
"SpatialPoints",
"sr",
"StatArea",
"Type",
"Value",
"X",
"Y",
"fortify",
"full_join",
"gBuffer",
"gCentroid",
"gear",
"gearname",
"Gear",
"get.shade",
"group",
"hist",
"inCRS",
"jsSections",
"lat",
"latex.math.bold",
"latex.nline",
"layout",
"left_join",
"legend",
"lines",
"long",
"matplot",
"mcmc",
"mcmc.biomass.file",
"mcmc.file",
"mcmc.fishing.mort.file",
"mcmc.fishing.mort.u.file",
"mcmc.natural.mort.file",
"mcmc.proj.file",
"mcmc.recr.devs.file",
"mcmc.recr.file",
"mcmc.vuln.biomass.file",
"median",
"mdl_cls",
"model.dir",
"mdl_lst_cls",
"mtext",
"odbcClose",
"odbcConnectAccess",
"outCRS",
"over",
"pairs",
"panel.smooth",
"par",
"par.file",
"p1",
"p2",
"plot",
"plot.new",
"plot.window",
"points",
"polygon",
"ran",
"read.csv",
"read.rep",
"readOGR",
"read_csv",
"rect",
"region",
"rep.file",
"rgb",
"right_join",
"sanitize",
"sectionSub",
"set.mfrow",
"spTransform",
"sqlFetch",
"starter.file.name",
"symbols",
"tibble",
"title",
"transmute",
"unite",
"value",
"variance.results",
"weighted.mean",
"window",
"x",
"y",
"year",
"yrRange",
"variable",
"area",
"sex",
"Age",
"Year",
"year_ind",
"Weight",
"muWeight",
"Number",
"Proportion",
"MeanAge",
"sBar",
"GroupID",
"Fixed",
"V1",
"V2",
"V3",
"V4",
"numest",
"param",
"Param 1",
"Param 2",
"Lower",
"Upper",
"wt",
"survey_abbrev",
"timing",
"Index",
"iyr",
"it",
"retro.dir",
"output.files",
"iscam.exe.file",
"linux.pipe.to.log",
"dos.pipe.to.log",
"Sensitivity",
"Biomass (t)",
"allRegions",
"jsSections",
"V1",

".x", "1", "2", ":=", "Area", "Discarded", "Fleet", "Landings", "MPD", "Median", "residual",
"Year", "range", "coord_cartesian", "errbar_width", "expansion", "geom_col", "geom_hline",
"geom_segment", "geom_smooth", "guide_legend", "guides", "ival",
"med", "med_rt", "phz", "priortype",
"scale_size_area", "scale_x_continuous", "survey_name",

"Median residual", "Sign", "TAC", "Year range", "age", "base_model", "ci_df", "end_year",
"fleet", "gear_ind", "gear_num", "hi", "hi_rt", "hi_sbt", "hi_value", "is_selex",
"iscam_palette", "latex.amp", "latex.mcol", "lb", "lo", "lo_rt", "lo_sbt", "lo_value", "lomed",
"mcmc.age.fits.file", "mcmc.index.fits.file", "mcmc.sel.file", "mdl_grp_cls",
"med_sbt", "medhi", "mpd.proj.file", "msl_cls", "plot_catch", "post", "posterior", "prior",
"priormeanlog", "priorsd", "prop", "prop.x", "prop.y", "quant", "quants",
"species_common_name", "start_year", "tab", "tac", "tso_quants", "ub", "val", "yearspan",
"yintercept"

))
